/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as AddressTestContractJson } from "../AddressTest.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace AddressTestTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    prefix: {
      params: CallContractParams<{ address: Address }>;
      result: CallContractResult<HexString>;
    };
    test: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    prefix: {
      params: SignExecuteContractMethodParams<{ address: Address }>;
      result: SignExecuteScriptTxResult;
    };
    test: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<AddressTestInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): AddressTestInstance {
    return new AddressTestInstance(address);
  }

  tests = {
    prefix: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { address: Address }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "prefix", params, getContractByCodeHash);
    },
    test: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "testArgs" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "test",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const AddressTest = new Factory(
  Contract.fromJson(
    AddressTestContractJson,
    "=8-2+2f=39-1+a=506+7e011b54657374207375636365737366756c20666f722041646472657373",
    "f581f1ea92f8da236b32390fb91afea41631de8a56f7d5cde42d12947f67d8d7",
    AllStructs
  )
);
registerContract(AddressTest);

// Use this class to interact with the blockchain
export class AddressTestInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<AddressTestTypes.State> {
    return fetchContractState(AddressTest, this);
  }

  view = {
    prefix: async (
      params: AddressTestTypes.CallMethodParams<"prefix">
    ): Promise<AddressTestTypes.CallMethodResult<"prefix">> => {
      return callMethod(
        AddressTest,
        this,
        "prefix",
        params,
        getContractByCodeHash
      );
    },
    test: async (
      params?: AddressTestTypes.CallMethodParams<"test">
    ): Promise<AddressTestTypes.CallMethodResult<"test">> => {
      return callMethod(
        AddressTest,
        this,
        "test",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    prefix: async (
      params: AddressTestTypes.SignExecuteMethodParams<"prefix">
    ): Promise<AddressTestTypes.SignExecuteMethodResult<"prefix">> => {
      return signExecuteMethod(AddressTest, this, "prefix", params);
    },
    test: async (
      params: AddressTestTypes.SignExecuteMethodParams<"test">
    ): Promise<AddressTestTypes.SignExecuteMethodResult<"test">> => {
      return signExecuteMethod(AddressTest, this, "test", params);
    },
  };

  async multicall<Calls extends AddressTestTypes.MultiCallParams>(
    calls: Calls
  ): Promise<AddressTestTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends AddressTestTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<AddressTestTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | AddressTestTypes.MultiCallParams
      | AddressTestTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      AddressTest,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
