/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as AdminContractJson } from "../Admin.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace AdminTypes {
  export type Fields = {
    admin: Address;
  };

  export type State = ContractState<Fields>;

  export type AdminUpdatedEvent = ContractEvent<{
    previous: Address;
    new: Address;
  }>;

  export interface CallMethodTable {
    updateAdmin: {
      params: CallContractParams<{ newAdmin: Address }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    updateAdmin: {
      params: SignExecuteContractMethodParams<{ newAdmin: Address }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<AdminInstance, AdminTypes.Fields> {
  encodeFields(fields: AdminTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { AdminUpdated: 0 };

  at(address: string): AdminInstance {
    return new AdminInstance(address);
  }

  tests = {
    updateAdmin: async (
      params: TestContractParamsWithoutMaps<
        AdminTypes.Fields,
        { newAdmin: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateAdmin", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: AdminTypes.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Admin = new Factory(
  Contract.fromJson(
    AdminContractJson,
    "",
    "9da5f16f66434d1a0e0d2f48b0c2300ab14faaef9f7718f9c8231dd866fde62b",
    AllStructs
  )
);
registerContract(Admin);

// Use this class to interact with the blockchain
export class AdminInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<AdminTypes.State> {
    return fetchContractState(Admin, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeAdminUpdatedEvent(
    options: EventSubscribeOptions<AdminTypes.AdminUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Admin.contract,
      this,
      options,
      "AdminUpdated",
      fromCount
    );
  }

  view = {
    updateAdmin: async (
      params: AdminTypes.CallMethodParams<"updateAdmin">
    ): Promise<AdminTypes.CallMethodResult<"updateAdmin">> => {
      return callMethod(
        Admin,
        this,
        "updateAdmin",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    updateAdmin: async (
      params: AdminTypes.SignExecuteMethodParams<"updateAdmin">
    ): Promise<AdminTypes.SignExecuteMethodResult<"updateAdmin">> => {
      return signExecuteMethod(Admin, this, "updateAdmin", params);
    },
  };
}
