/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as ArrayContractJson } from "../Array.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace ArrayTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    test: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    test: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<ArrayInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): ArrayInstance {
    return new ArrayInstance(address);
  }

  tests = {
    test: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "test",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Array = new Factory(
  Contract.fromJson(
    ArrayContractJson,
    "=6-2+8f=13-1+6=216+7e011954657374207375636365737366756c20666f72204172726179",
    "37d40ebc4ad858588432a0cb1022f22e9cd5ad6a744d4ae5fb8388a1e5b61cea",
    AllStructs
  )
);
registerContract(Array);

// Use this class to interact with the blockchain
export class ArrayInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ArrayTypes.State> {
    return fetchContractState(Array, this);
  }

  view = {
    test: async (
      params?: ArrayTypes.CallMethodParams<"test">
    ): Promise<ArrayTypes.CallMethodResult<"test">> => {
      return callMethod(
        Array,
        this,
        "test",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    test: async (
      params: ArrayTypes.SignExecuteMethodParams<"test">
    ): Promise<ArrayTypes.SignExecuteMethodResult<"test">> => {
      return signExecuteMethod(Array, this, "test", params);
    },
  };
}
