/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as AssetFunctionsContractJson } from "../AssetFunctions.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace AssetFunctionsTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    burn: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    lock: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    deposit: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    burn: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    lock: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<AssetFunctionsInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): AssetFunctionsInstance {
    return new AssetFunctionsInstance(address);
  }

  tests = {
    burn: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "burn",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    lock: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { amount: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "lock", params, getContractByCodeHash);
    },
    withdraw: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { amount: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    deposit: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { amount: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const AssetFunctions = new Factory(
  Contract.fromJson(
    AssetFunctionsContractJson,
    "",
    "88236b38440622ec6e1c24d85567bd1f2ecb587c0caa01b3e24d872aa932db88",
    AllStructs
  )
);
registerContract(AssetFunctions);

// Use this class to interact with the blockchain
export class AssetFunctionsInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<AssetFunctionsTypes.State> {
    return fetchContractState(AssetFunctions, this);
  }

  view = {
    burn: async (
      params?: AssetFunctionsTypes.CallMethodParams<"burn">
    ): Promise<AssetFunctionsTypes.CallMethodResult<"burn">> => {
      return callMethod(
        AssetFunctions,
        this,
        "burn",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    lock: async (
      params: AssetFunctionsTypes.CallMethodParams<"lock">
    ): Promise<AssetFunctionsTypes.CallMethodResult<"lock">> => {
      return callMethod(
        AssetFunctions,
        this,
        "lock",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: AssetFunctionsTypes.CallMethodParams<"withdraw">
    ): Promise<AssetFunctionsTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        AssetFunctions,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: AssetFunctionsTypes.CallMethodParams<"deposit">
    ): Promise<AssetFunctionsTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        AssetFunctions,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    burn: async (
      params: AssetFunctionsTypes.SignExecuteMethodParams<"burn">
    ): Promise<AssetFunctionsTypes.SignExecuteMethodResult<"burn">> => {
      return signExecuteMethod(AssetFunctions, this, "burn", params);
    },
    lock: async (
      params: AssetFunctionsTypes.SignExecuteMethodParams<"lock">
    ): Promise<AssetFunctionsTypes.SignExecuteMethodResult<"lock">> => {
      return signExecuteMethod(AssetFunctions, this, "lock", params);
    },
    withdraw: async (
      params: AssetFunctionsTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<AssetFunctionsTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(AssetFunctions, this, "withdraw", params);
    },
    deposit: async (
      params: AssetFunctionsTypes.SignExecuteMethodParams<"deposit">
    ): Promise<AssetFunctionsTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(AssetFunctions, this, "deposit", params);
    },
  };
}
