/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as BankContractJson } from "../Bank.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace BankTypes {
  export type Fields = {
    totalDeposits: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    deposit: {
      params: CallContractParams<{ depositor: Address }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    deposit: {
      params: SignExecuteContractMethodParams<{ depositor: Address }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<BankInstance, BankTypes.Fields> {
  encodeFields(fields: BankTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  consts = { ErrorCodes: { InsufficientFunds: BigInt("0") } };

  at(address: string): BankInstance {
    return new BankInstance(address);
  }

  tests = {
    deposit: async (
      params: TestContractParamsWithoutMaps<
        BankTypes.Fields,
        { depositor: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        BankTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: BankTypes.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Bank = new Factory(
  Contract.fromJson(
    BankContractJson,
    "",
    "71ae38151a7762d3767975964982066bd733753e940b274e13c8b5e69b87480c",
    AllStructs
  )
);
registerContract(Bank);

// Use this class to interact with the blockchain
export class BankInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BankTypes.State> {
    return fetchContractState(Bank, this);
  }

  view = {
    deposit: async (
      params: BankTypes.CallMethodParams<"deposit">
    ): Promise<BankTypes.CallMethodResult<"deposit">> => {
      return callMethod(Bank, this, "deposit", params, getContractByCodeHash);
    },
    withdraw: async (
      params: BankTypes.CallMethodParams<"withdraw">
    ): Promise<BankTypes.CallMethodResult<"withdraw">> => {
      return callMethod(Bank, this, "withdraw", params, getContractByCodeHash);
    },
  };

  transact = {
    deposit: async (
      params: BankTypes.SignExecuteMethodParams<"deposit">
    ): Promise<BankTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(Bank, this, "deposit", params);
    },
    withdraw: async (
      params: BankTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<BankTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(Bank, this, "withdraw", params);
    },
  };
}
