/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as BurnContractJson } from "../Burn.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace BurnTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    burn: {
      params: CallContractParams<{ caller: Address; tokenId: HexString }>;
      result: CallContractResult<null>;
    };
    main: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    burn: {
      params: SignExecuteContractMethodParams<{
        caller: Address;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    main: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<BurnInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): BurnInstance {
    return new BurnInstance(address);
  }

  tests = {
    burn: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { caller: Address; tokenId: HexString }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burn", params, getContractByCodeHash);
    },
    main: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { tokenId: HexString }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "main", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Burn = new Factory(
  Contract.fromJson(
    BurnContractJson,
    "",
    "c450bef21a0fbee19e8ba57d1b95939bb704eda48af4b216748a946c0ab99e04",
    AllStructs
  )
);
registerContract(Burn);

// Use this class to interact with the blockchain
export class BurnInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BurnTypes.State> {
    return fetchContractState(Burn, this);
  }

  view = {
    burn: async (
      params: BurnTypes.CallMethodParams<"burn">
    ): Promise<BurnTypes.CallMethodResult<"burn">> => {
      return callMethod(Burn, this, "burn", params, getContractByCodeHash);
    },
    main: async (
      params: BurnTypes.CallMethodParams<"main">
    ): Promise<BurnTypes.CallMethodResult<"main">> => {
      return callMethod(Burn, this, "main", params, getContractByCodeHash);
    },
  };

  transact = {
    burn: async (
      params: BurnTypes.SignExecuteMethodParams<"burn">
    ): Promise<BurnTypes.SignExecuteMethodResult<"burn">> => {
      return signExecuteMethod(Burn, this, "burn", params);
    },
    main: async (
      params: BurnTypes.SignExecuteMethodParams<"main">
    ): Promise<BurnTypes.SignExecuteMethodResult<"main">> => {
      return signExecuteMethod(Burn, this, "main", params);
    },
  };
}
