/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CarContractJson } from "../Car.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CarTypes {
  export type Fields = {
    model: HexString;
    year: bigint;
    price: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    updatePrice: {
      params: CallContractParams<{ newPrice: bigint }>;
      result: CallContractResult<null>;
    };
    getCarInfo: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    updatePrice: {
      params: SignExecuteContractMethodParams<{ newPrice: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getCarInfo: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<CarInstance, CarTypes.Fields> {
  encodeFields(fields: CarTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): CarInstance {
    return new CarInstance(address);
  }

  tests = {
    updatePrice: async (
      params: TestContractParamsWithoutMaps<
        CarTypes.Fields,
        { newPrice: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updatePrice", params, getContractByCodeHash);
    },
    getCarInfo: async (
      params: Omit<
        TestContractParamsWithoutMaps<CarTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint, bigint]>> => {
      return testMethod(this, "getCarInfo", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: CarTypes.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Car = new Factory(
  Contract.fromJson(
    CarContractJson,
    "",
    "2d3fda158b1ee9ca828ca9cdab0333a9d6607ab0b80726606df0a94fc066ce0b",
    AllStructs
  )
);
registerContract(Car);

// Use this class to interact with the blockchain
export class CarInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CarTypes.State> {
    return fetchContractState(Car, this);
  }

  view = {
    updatePrice: async (
      params: CarTypes.CallMethodParams<"updatePrice">
    ): Promise<CarTypes.CallMethodResult<"updatePrice">> => {
      return callMethod(
        Car,
        this,
        "updatePrice",
        params,
        getContractByCodeHash
      );
    },
    getCarInfo: async (
      params?: CarTypes.CallMethodParams<"getCarInfo">
    ): Promise<CarTypes.CallMethodResult<"getCarInfo">> => {
      return callMethod(
        Car,
        this,
        "getCarInfo",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    updatePrice: async (
      params: CarTypes.SignExecuteMethodParams<"updatePrice">
    ): Promise<CarTypes.SignExecuteMethodResult<"updatePrice">> => {
      return signExecuteMethod(Car, this, "updatePrice", params);
    },
    getCarInfo: async (
      params: CarTypes.SignExecuteMethodParams<"getCarInfo">
    ): Promise<CarTypes.SignExecuteMethodResult<"getCarInfo">> => {
      return signExecuteMethod(Car, this, "getCarInfo", params);
    },
  };

  async multicall<Calls extends CarTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CarTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CarTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CarTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends CarTypes.MultiCallParams | CarTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Car, this, callss, getContractByCodeHash);
  }
}
