/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CarFactoryContractJson } from "../CarFactory.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CarFactoryTypes {
  export type Fields = {
    carAddress: Address;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    createCar: {
      params: CallContractParams<{
        carByteCode: HexString;
        model: HexString;
        year: bigint;
        price: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    copyCreateCar: {
      params: CallContractParams<{
        carContractId: HexString;
        model: HexString;
        year: bigint;
        price: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    copyCreateCarWithToken: {
      params: CallContractParams<{
        carContractId: HexString;
        model: HexString;
        year: bigint;
        price: bigint;
        tokenAmount: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createCar: {
      params: SignExecuteContractMethodParams<{
        carByteCode: HexString;
        model: HexString;
        year: bigint;
        price: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    copyCreateCar: {
      params: SignExecuteContractMethodParams<{
        carContractId: HexString;
        model: HexString;
        year: bigint;
        price: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    copyCreateCarWithToken: {
      params: SignExecuteContractMethodParams<{
        carContractId: HexString;
        model: HexString;
        year: bigint;
        price: bigint;
        tokenAmount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  CarFactoryInstance,
  CarFactoryTypes.Fields
> {
  encodeFields(fields: CarFactoryTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): CarFactoryInstance {
    return new CarFactoryInstance(address);
  }

  tests = {
    createCar: async (
      params: TestContractParamsWithoutMaps<
        CarFactoryTypes.Fields,
        {
          carByteCode: HexString;
          model: HexString;
          year: bigint;
          price: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "createCar", params, getContractByCodeHash);
    },
    copyCreateCar: async (
      params: TestContractParamsWithoutMaps<
        CarFactoryTypes.Fields,
        {
          carContractId: HexString;
          model: HexString;
          year: bigint;
          price: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "copyCreateCar", params, getContractByCodeHash);
    },
    copyCreateCarWithToken: async (
      params: TestContractParamsWithoutMaps<
        CarFactoryTypes.Fields,
        {
          carContractId: HexString;
          model: HexString;
          year: bigint;
          price: bigint;
          tokenAmount: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "copyCreateCarWithToken",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: CarFactoryTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CarFactory = new Factory(
  Contract.fromJson(
    CarFactoryContractJson,
    "",
    "db9759978478498a71d105c1b78a0a1306d5fb1211309132215021c8a1b2fb46",
    AllStructs
  )
);
registerContract(CarFactory);

// Use this class to interact with the blockchain
export class CarFactoryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CarFactoryTypes.State> {
    return fetchContractState(CarFactory, this);
  }

  view = {
    createCar: async (
      params: CarFactoryTypes.CallMethodParams<"createCar">
    ): Promise<CarFactoryTypes.CallMethodResult<"createCar">> => {
      return callMethod(
        CarFactory,
        this,
        "createCar",
        params,
        getContractByCodeHash
      );
    },
    copyCreateCar: async (
      params: CarFactoryTypes.CallMethodParams<"copyCreateCar">
    ): Promise<CarFactoryTypes.CallMethodResult<"copyCreateCar">> => {
      return callMethod(
        CarFactory,
        this,
        "copyCreateCar",
        params,
        getContractByCodeHash
      );
    },
    copyCreateCarWithToken: async (
      params: CarFactoryTypes.CallMethodParams<"copyCreateCarWithToken">
    ): Promise<CarFactoryTypes.CallMethodResult<"copyCreateCarWithToken">> => {
      return callMethod(
        CarFactory,
        this,
        "copyCreateCarWithToken",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createCar: async (
      params: CarFactoryTypes.SignExecuteMethodParams<"createCar">
    ): Promise<CarFactoryTypes.SignExecuteMethodResult<"createCar">> => {
      return signExecuteMethod(CarFactory, this, "createCar", params);
    },
    copyCreateCar: async (
      params: CarFactoryTypes.SignExecuteMethodParams<"copyCreateCar">
    ): Promise<CarFactoryTypes.SignExecuteMethodResult<"copyCreateCar">> => {
      return signExecuteMethod(CarFactory, this, "copyCreateCar", params);
    },
    copyCreateCarWithToken: async (
      params: CarFactoryTypes.SignExecuteMethodParams<"copyCreateCarWithToken">
    ): Promise<
      CarFactoryTypes.SignExecuteMethodResult<"copyCreateCarWithToken">
    > => {
      return signExecuteMethod(
        CarFactory,
        this,
        "copyCreateCarWithToken",
        params
      );
    },
  };

  async multicall<Calls extends CarFactoryTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CarFactoryTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CarFactoryTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CarFactoryTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | CarFactoryTypes.MultiCallParams
      | CarFactoryTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      CarFactory,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
