/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CheckExternalContractJson } from "../CheckExternal.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CheckExternalTypes {
  export type Fields = {
    owner: Address;
    value: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getValue: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    setValue: {
      params: CallContractParams<{ v: bigint }>;
      result: CallContractResult<null>;
    };
    setValueUnsafe: {
      params: CallContractParams<{ v: bigint }>;
      result: CallContractResult<null>;
    };
    getValuePrivate: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getValue: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setValue: {
      params: SignExecuteContractMethodParams<{ v: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    setValueUnsafe: {
      params: SignExecuteContractMethodParams<{ v: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getValuePrivate: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  CheckExternalInstance,
  CheckExternalTypes.Fields
> {
  encodeFields(fields: CheckExternalTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): CheckExternalInstance {
    return new CheckExternalInstance(address);
  }

  tests = {
    getValue: async (
      params: Omit<
        TestContractParamsWithoutMaps<CheckExternalTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getValue", params, getContractByCodeHash);
    },
    setValue: async (
      params: TestContractParamsWithoutMaps<
        CheckExternalTypes.Fields,
        { v: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setValue", params, getContractByCodeHash);
    },
    setValueUnsafe: async (
      params: TestContractParamsWithoutMaps<
        CheckExternalTypes.Fields,
        { v: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setValueUnsafe", params, getContractByCodeHash);
    },
    getValuePrivate: async (
      params: Omit<
        TestContractParamsWithoutMaps<CheckExternalTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getValuePrivate", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: CheckExternalTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CheckExternal = new Factory(
  Contract.fromJson(
    CheckExternalContractJson,
    "",
    "48a6579f3a1d24bfc543af68c864106b67b3165a4b00b9f4e59abe2e3831366b",
    AllStructs
  )
);
registerContract(CheckExternal);

// Use this class to interact with the blockchain
export class CheckExternalInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CheckExternalTypes.State> {
    return fetchContractState(CheckExternal, this);
  }

  view = {
    getValue: async (
      params?: CheckExternalTypes.CallMethodParams<"getValue">
    ): Promise<CheckExternalTypes.CallMethodResult<"getValue">> => {
      return callMethod(
        CheckExternal,
        this,
        "getValue",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setValue: async (
      params: CheckExternalTypes.CallMethodParams<"setValue">
    ): Promise<CheckExternalTypes.CallMethodResult<"setValue">> => {
      return callMethod(
        CheckExternal,
        this,
        "setValue",
        params,
        getContractByCodeHash
      );
    },
    setValueUnsafe: async (
      params: CheckExternalTypes.CallMethodParams<"setValueUnsafe">
    ): Promise<CheckExternalTypes.CallMethodResult<"setValueUnsafe">> => {
      return callMethod(
        CheckExternal,
        this,
        "setValueUnsafe",
        params,
        getContractByCodeHash
      );
    },
    getValuePrivate: async (
      params?: CheckExternalTypes.CallMethodParams<"getValuePrivate">
    ): Promise<CheckExternalTypes.CallMethodResult<"getValuePrivate">> => {
      return callMethod(
        CheckExternal,
        this,
        "getValuePrivate",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getValue: async (
      params: CheckExternalTypes.SignExecuteMethodParams<"getValue">
    ): Promise<CheckExternalTypes.SignExecuteMethodResult<"getValue">> => {
      return signExecuteMethod(CheckExternal, this, "getValue", params);
    },
    setValue: async (
      params: CheckExternalTypes.SignExecuteMethodParams<"setValue">
    ): Promise<CheckExternalTypes.SignExecuteMethodResult<"setValue">> => {
      return signExecuteMethod(CheckExternal, this, "setValue", params);
    },
    setValueUnsafe: async (
      params: CheckExternalTypes.SignExecuteMethodParams<"setValueUnsafe">
    ): Promise<
      CheckExternalTypes.SignExecuteMethodResult<"setValueUnsafe">
    > => {
      return signExecuteMethod(CheckExternal, this, "setValueUnsafe", params);
    },
    getValuePrivate: async (
      params: CheckExternalTypes.SignExecuteMethodParams<"getValuePrivate">
    ): Promise<
      CheckExternalTypes.SignExecuteMethodResult<"getValuePrivate">
    > => {
      return signExecuteMethod(CheckExternal, this, "getValuePrivate", params);
    },
  };

  async multicall<Calls extends CheckExternalTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CheckExternalTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CheckExternalTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CheckExternalTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | CheckExternalTypes.MultiCallParams
      | CheckExternalTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      CheckExternal,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
