/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CompanyContractJson } from "../Company.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CompanyTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    getStatus: {
      params: CallContractParams<{ contractId: HexString }>;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: CallContractParams<{ contractId: HexString }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getStatus: {
      params: SignExecuteContractMethodParams<{ contractId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: SignExecuteContractMethodParams<{ contractId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<CompanyInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): CompanyInstance {
    return new CompanyInstance(address);
  }

  tests = {
    getStatus: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { contractId: HexString }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getStatus", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { contractId: HexString }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Company = new Factory(
  Contract.fromJson(
    CompanyContractJson,
    "",
    "626bee02f289852e7c8a52c6e594f72d437f62467379efc41426d2921fa4732b",
    AllStructs
  )
);
registerContract(Company);

// Use this class to interact with the blockchain
export class CompanyInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CompanyTypes.State> {
    return fetchContractState(Company, this);
  }

  view = {
    getStatus: async (
      params: CompanyTypes.CallMethodParams<"getStatus">
    ): Promise<CompanyTypes.CallMethodResult<"getStatus">> => {
      return callMethod(
        Company,
        this,
        "getStatus",
        params,
        getContractByCodeHash
      );
    },
    getName: async (
      params: CompanyTypes.CallMethodParams<"getName">
    ): Promise<CompanyTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Company,
        this,
        "getName",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getStatus: async (
      params: CompanyTypes.SignExecuteMethodParams<"getStatus">
    ): Promise<CompanyTypes.SignExecuteMethodResult<"getStatus">> => {
      return signExecuteMethod(Company, this, "getStatus", params);
    },
    getName: async (
      params: CompanyTypes.SignExecuteMethodParams<"getName">
    ): Promise<CompanyTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(Company, this, "getName", params);
    },
  };

  async multicall<Calls extends CompanyTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CompanyTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CompanyTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CompanyTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends CompanyTypes.MultiCallParams | CompanyTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Company, this, callss, getContractByCodeHash);
  }
}
