/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as ConditionalContractJson } from "../Conditional.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace ConditionalTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    ifExpr: {
      params: CallContractParams<{ a: bigint }>;
      result: CallContractResult<HexString>;
    };
    ifStmt: {
      params: CallContractParams<{ a: bigint }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    ifExpr: {
      params: SignExecuteContractMethodParams<{ a: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    ifStmt: {
      params: SignExecuteContractMethodParams<{ a: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<ConditionalInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): ConditionalInstance {
    return new ConditionalInstance(address);
  }

  tests = {
    ifExpr: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { a: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "ifExpr", params, getContractByCodeHash);
    },
    ifStmt: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { a: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "ifStmt", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Conditional = new Factory(
  Contract.fromJson(
    ConditionalContractJson,
    "",
    "b487a02e74fcd2e01d377ab305bd75f107db7dbe7a8ffc5bcf45682ee45b616c",
    AllStructs
  )
);
registerContract(Conditional);

// Use this class to interact with the blockchain
export class ConditionalInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ConditionalTypes.State> {
    return fetchContractState(Conditional, this);
  }

  view = {
    ifExpr: async (
      params: ConditionalTypes.CallMethodParams<"ifExpr">
    ): Promise<ConditionalTypes.CallMethodResult<"ifExpr">> => {
      return callMethod(
        Conditional,
        this,
        "ifExpr",
        params,
        getContractByCodeHash
      );
    },
    ifStmt: async (
      params: ConditionalTypes.CallMethodParams<"ifStmt">
    ): Promise<ConditionalTypes.CallMethodResult<"ifStmt">> => {
      return callMethod(
        Conditional,
        this,
        "ifStmt",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    ifExpr: async (
      params: ConditionalTypes.SignExecuteMethodParams<"ifExpr">
    ): Promise<ConditionalTypes.SignExecuteMethodResult<"ifExpr">> => {
      return signExecuteMethod(Conditional, this, "ifExpr", params);
    },
    ifStmt: async (
      params: ConditionalTypes.SignExecuteMethodParams<"ifStmt">
    ): Promise<ConditionalTypes.SignExecuteMethodResult<"ifStmt">> => {
      return signExecuteMethod(Conditional, this, "ifStmt", params);
    },
  };

  async multicall<Calls extends ConditionalTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ConditionalTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends ConditionalTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<ConditionalTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | ConditionalTypes.MultiCallParams
      | ConditionalTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      Conditional,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
