/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CountersContractJson } from "../Counters.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace CountersTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    create: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    increase: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    currentCount: {
      params: CallContractParams<{ key: Address }>;
      result: CallContractResult<bigint>;
    };
    clear: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    create: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    increase: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    currentCount: {
      params: SignExecuteContractMethodParams<{ key: Address }>;
      result: SignExecuteScriptTxResult;
    };
    clear: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { counters?: Map<Address, bigint> };
}

class Factory extends ContractFactory<CountersInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): CountersInstance {
    return new CountersInstance(address);
  }

  tests = {
    create: async (
      params?: Omit<
        TestContractParams<never, never, CountersTypes.Maps>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResult<null, CountersTypes.Maps>> => {
      return testMethod(
        this,
        "create",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    increase: async (
      params?: Omit<
        TestContractParams<never, never, CountersTypes.Maps>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResult<null, CountersTypes.Maps>> => {
      return testMethod(
        this,
        "increase",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    currentCount: async (
      params: Omit<
        TestContractParams<never, { key: Address }, CountersTypes.Maps>,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint, CountersTypes.Maps>> => {
      return testMethod(this, "currentCount", params, getContractByCodeHash);
    },
    clear: async (
      params?: Omit<
        TestContractParams<never, never, CountersTypes.Maps>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResult<bigint, CountersTypes.Maps>> => {
      return testMethod(
        this,
        "clear",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: {},
    asset?: Asset,
    address?: string,
    maps?: CountersTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Counters = new Factory(
  Contract.fromJson(
    CountersContractJson,
    "=6-2+4=1-3=2-2+84=2+b=2+116=10-2+11=64+7a7e0214696e73657274206174206d617020706174683a2000=265-1+a=102+7a7e021472656d6f7665206174206d617020706174683a2000=12",
    "bb1fa96c57df58f8e384a48f3b0f1b42967108c5f2aa89b71db3c2d469972ccb",
    AllStructs
  )
);
registerContract(Counters);

// Use this class to interact with the blockchain
export class CountersInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    counters: new RalphMap<Address, bigint>(
      Counters.contract,
      this.contractId,
      "counters"
    ),
  };

  async fetchState(): Promise<CountersTypes.State> {
    return fetchContractState(Counters, this);
  }

  view = {
    create: async (
      params?: CountersTypes.CallMethodParams<"create">
    ): Promise<CountersTypes.CallMethodResult<"create">> => {
      return callMethod(
        Counters,
        this,
        "create",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    increase: async (
      params?: CountersTypes.CallMethodParams<"increase">
    ): Promise<CountersTypes.CallMethodResult<"increase">> => {
      return callMethod(
        Counters,
        this,
        "increase",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    currentCount: async (
      params: CountersTypes.CallMethodParams<"currentCount">
    ): Promise<CountersTypes.CallMethodResult<"currentCount">> => {
      return callMethod(
        Counters,
        this,
        "currentCount",
        params,
        getContractByCodeHash
      );
    },
    clear: async (
      params?: CountersTypes.CallMethodParams<"clear">
    ): Promise<CountersTypes.CallMethodResult<"clear">> => {
      return callMethod(
        Counters,
        this,
        "clear",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    create: async (
      params: CountersTypes.SignExecuteMethodParams<"create">
    ): Promise<CountersTypes.SignExecuteMethodResult<"create">> => {
      return signExecuteMethod(Counters, this, "create", params);
    },
    increase: async (
      params: CountersTypes.SignExecuteMethodParams<"increase">
    ): Promise<CountersTypes.SignExecuteMethodResult<"increase">> => {
      return signExecuteMethod(Counters, this, "increase", params);
    },
    currentCount: async (
      params: CountersTypes.SignExecuteMethodParams<"currentCount">
    ): Promise<CountersTypes.SignExecuteMethodResult<"currentCount">> => {
      return signExecuteMethod(Counters, this, "currentCount", params);
    },
    clear: async (
      params: CountersTypes.SignExecuteMethodParams<"clear">
    ): Promise<CountersTypes.SignExecuteMethodResult<"clear">> => {
      return signExecuteMethod(Counters, this, "clear", params);
    },
  };

  async multicall<Calls extends CountersTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CountersTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CountersTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CountersTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | CountersTypes.MultiCallParams
      | CountersTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      Counters,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
