/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CounterContractJson } from "../Counter.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CounterTypes {
  export type Fields = {
    counter: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    increase: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    increase: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<CounterInstance, CounterTypes.Fields> {
  encodeFields(fields: CounterTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): CounterInstance {
    return new CounterInstance(address);
  }

  tests = {
    increase: async (
      params: Omit<
        TestContractParamsWithoutMaps<CounterTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "increase", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: CounterTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Counter = new Factory(
  Contract.fromJson(
    CounterContractJson,
    "",
    "25bfef57ab064636404cf459647d2d97b3dfdd4e38d66410c1fd138b673be452",
    AllStructs
  )
);
registerContract(Counter);

// Use this class to interact with the blockchain
export class CounterInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CounterTypes.State> {
    return fetchContractState(Counter, this);
  }

  view = {
    increase: async (
      params?: CounterTypes.CallMethodParams<"increase">
    ): Promise<CounterTypes.CallMethodResult<"increase">> => {
      return callMethod(
        Counter,
        this,
        "increase",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    increase: async (
      params: CounterTypes.SignExecuteMethodParams<"increase">
    ): Promise<CounterTypes.SignExecuteMethodResult<"increase">> => {
      return signExecuteMethod(Counter, this, "increase", params);
    },
  };
}
