/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CryptographyFunctionsContractJson } from "../CryptographyFunctions.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CryptographyFunctionsTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    verifyHash: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    verifySignature: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    verifyEthEcRecover: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    verifyHash: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    verifySignature: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    verifyEthEcRecover: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<CryptographyFunctionsInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): CryptographyFunctionsInstance {
    return new CryptographyFunctionsInstance(address);
  }

  tests = {
    verifyHash: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "verifyHash",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    verifySignature: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "verifySignature",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    verifyEthEcRecover: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "verifyEthEcRecover",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CryptographyFunctions = new Factory(
  Contract.fromJson(
    CryptographyFunctionsContractJson,
    "",
    "3219704c52b1e9960913c67bfc91252716e9d4447ad6a0e67b6576a579ced572",
    AllStructs
  )
);
registerContract(CryptographyFunctions);

// Use this class to interact with the blockchain
export class CryptographyFunctionsInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CryptographyFunctionsTypes.State> {
    return fetchContractState(CryptographyFunctions, this);
  }

  view = {
    verifyHash: async (
      params?: CryptographyFunctionsTypes.CallMethodParams<"verifyHash">
    ): Promise<CryptographyFunctionsTypes.CallMethodResult<"verifyHash">> => {
      return callMethod(
        CryptographyFunctions,
        this,
        "verifyHash",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    verifySignature: async (
      params?: CryptographyFunctionsTypes.CallMethodParams<"verifySignature">
    ): Promise<
      CryptographyFunctionsTypes.CallMethodResult<"verifySignature">
    > => {
      return callMethod(
        CryptographyFunctions,
        this,
        "verifySignature",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    verifyEthEcRecover: async (
      params?: CryptographyFunctionsTypes.CallMethodParams<"verifyEthEcRecover">
    ): Promise<
      CryptographyFunctionsTypes.CallMethodResult<"verifyEthEcRecover">
    > => {
      return callMethod(
        CryptographyFunctions,
        this,
        "verifyEthEcRecover",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    verifyHash: async (
      params: CryptographyFunctionsTypes.SignExecuteMethodParams<"verifyHash">
    ): Promise<
      CryptographyFunctionsTypes.SignExecuteMethodResult<"verifyHash">
    > => {
      return signExecuteMethod(
        CryptographyFunctions,
        this,
        "verifyHash",
        params
      );
    },
    verifySignature: async (
      params: CryptographyFunctionsTypes.SignExecuteMethodParams<"verifySignature">
    ): Promise<
      CryptographyFunctionsTypes.SignExecuteMethodResult<"verifySignature">
    > => {
      return signExecuteMethod(
        CryptographyFunctions,
        this,
        "verifySignature",
        params
      );
    },
    verifyEthEcRecover: async (
      params: CryptographyFunctionsTypes.SignExecuteMethodParams<"verifyEthEcRecover">
    ): Promise<
      CryptographyFunctionsTypes.SignExecuteMethodResult<"verifyEthEcRecover">
    > => {
      return signExecuteMethod(
        CryptographyFunctions,
        this,
        "verifyEthEcRecover",
        params
      );
    },
  };
}
