/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CustomerContractJson } from "../Customer.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace CustomerTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    makeDeposit: {
      params: CallContractParams<{ bank: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    makeDeposit: {
      params: SignExecuteContractMethodParams<{ bank: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<CustomerInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): CustomerInstance {
    return new CustomerInstance(address);
  }

  tests = {
    makeDeposit: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { bank: HexString }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "makeDeposit", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Customer = new Factory(
  Contract.fromJson(
    CustomerContractJson,
    "",
    "079469f831c04da0c47fe4525ecdf660a2cca687634399c8cefd1016187e0c0e",
    AllStructs
  )
);
registerContract(Customer);

// Use this class to interact with the blockchain
export class CustomerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CustomerTypes.State> {
    return fetchContractState(Customer, this);
  }

  view = {
    makeDeposit: async (
      params: CustomerTypes.CallMethodParams<"makeDeposit">
    ): Promise<CustomerTypes.CallMethodResult<"makeDeposit">> => {
      return callMethod(
        Customer,
        this,
        "makeDeposit",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    makeDeposit: async (
      params: CustomerTypes.SignExecuteMethodParams<"makeDeposit">
    ): Promise<CustomerTypes.SignExecuteMethodResult<"makeDeposit">> => {
      return signExecuteMethod(Customer, this, "makeDeposit", params);
    },
  };
}
