/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DirectorContractJson } from "../Director.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace DirectorTypes {
  export type Fields = {
    name: HexString;
    id: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    pay: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<bigint>;
    };
    status: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getManagementLevel: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    pay: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    status: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getManagementLevel: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<DirectorInstance, DirectorTypes.Fields> {
  encodeFields(fields: DirectorTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): DirectorInstance {
    return new DirectorInstance(address);
  }

  tests = {
    pay: async (
      params: TestContractParamsWithoutMaps<
        DirectorTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "pay", params, getContractByCodeHash);
    },
    status: async (
      params: Omit<
        TestContractParamsWithoutMaps<DirectorTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "status", params, getContractByCodeHash);
    },
    getManagementLevel: async (
      params: Omit<
        TestContractParamsWithoutMaps<DirectorTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getManagementLevel",
        params,
        getContractByCodeHash
      );
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<DirectorTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getId: async (
      params: Omit<
        TestContractParamsWithoutMaps<DirectorTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getId", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: DirectorTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Director = new Factory(
  Contract.fromJson(
    DirectorContractJson,
    "",
    "2d094b9e73c8f0c3584a45d119653e70fb9fce8b5c3ab37de3838bb6a4df09f9",
    AllStructs
  )
);
registerContract(Director);

// Use this class to interact with the blockchain
export class DirectorInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DirectorTypes.State> {
    return fetchContractState(Director, this);
  }

  view = {
    pay: async (
      params: DirectorTypes.CallMethodParams<"pay">
    ): Promise<DirectorTypes.CallMethodResult<"pay">> => {
      return callMethod(Director, this, "pay", params, getContractByCodeHash);
    },
    status: async (
      params?: DirectorTypes.CallMethodParams<"status">
    ): Promise<DirectorTypes.CallMethodResult<"status">> => {
      return callMethod(
        Director,
        this,
        "status",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getManagementLevel: async (
      params?: DirectorTypes.CallMethodParams<"getManagementLevel">
    ): Promise<DirectorTypes.CallMethodResult<"getManagementLevel">> => {
      return callMethod(
        Director,
        this,
        "getManagementLevel",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: DirectorTypes.CallMethodParams<"getName">
    ): Promise<DirectorTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Director,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getId: async (
      params?: DirectorTypes.CallMethodParams<"getId">
    ): Promise<DirectorTypes.CallMethodResult<"getId">> => {
      return callMethod(
        Director,
        this,
        "getId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    pay: async (
      params: DirectorTypes.SignExecuteMethodParams<"pay">
    ): Promise<DirectorTypes.SignExecuteMethodResult<"pay">> => {
      return signExecuteMethod(Director, this, "pay", params);
    },
    status: async (
      params: DirectorTypes.SignExecuteMethodParams<"status">
    ): Promise<DirectorTypes.SignExecuteMethodResult<"status">> => {
      return signExecuteMethod(Director, this, "status", params);
    },
    getManagementLevel: async (
      params: DirectorTypes.SignExecuteMethodParams<"getManagementLevel">
    ): Promise<DirectorTypes.SignExecuteMethodResult<"getManagementLevel">> => {
      return signExecuteMethod(Director, this, "getManagementLevel", params);
    },
    getName: async (
      params: DirectorTypes.SignExecuteMethodParams<"getName">
    ): Promise<DirectorTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(Director, this, "getName", params);
    },
    getId: async (
      params: DirectorTypes.SignExecuteMethodParams<"getId">
    ): Promise<DirectorTypes.SignExecuteMethodResult<"getId">> => {
      return signExecuteMethod(Director, this, "getId", params);
    },
  };

  async multicall<Calls extends DirectorTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DirectorTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DirectorTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DirectorTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | DirectorTypes.MultiCallParams
      | DirectorTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      Director,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
