/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DomainContractJson } from "../Domain.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace DomainTypes {
  export type Fields = {
    url: HexString;
    subDomainTemplateId: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    createSubDomain: {
      params: CallContractParams<{ subDomainUrl: HexString }>;
      result: CallContractResult<Address>;
    };
    getSubDomain: {
      params: CallContractParams<{ subDomainUrl: HexString }>;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createSubDomain: {
      params: SignExecuteContractMethodParams<{ subDomainUrl: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    getSubDomain: {
      params: SignExecuteContractMethodParams<{ subDomainUrl: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<DomainInstance, DomainTypes.Fields> {
  encodeFields(fields: DomainTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): DomainInstance {
    return new DomainInstance(address);
  }

  tests = {
    createSubDomain: async (
      params: TestContractParamsWithoutMaps<
        DomainTypes.Fields,
        { subDomainUrl: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "createSubDomain", params, getContractByCodeHash);
    },
    getSubDomain: async (
      params: TestContractParamsWithoutMaps<
        DomainTypes.Fields,
        { subDomainUrl: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getSubDomain", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: DomainTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Domain = new Factory(
  Contract.fromJson(
    DomainContractJson,
    "",
    "f5f9e5d2d83b98a5e1c74cbb91905518fd4eb6a35be2014e506e8b5e63927f4f",
    AllStructs
  )
);
registerContract(Domain);

// Use this class to interact with the blockchain
export class DomainInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DomainTypes.State> {
    return fetchContractState(Domain, this);
  }

  view = {
    createSubDomain: async (
      params: DomainTypes.CallMethodParams<"createSubDomain">
    ): Promise<DomainTypes.CallMethodResult<"createSubDomain">> => {
      return callMethod(
        Domain,
        this,
        "createSubDomain",
        params,
        getContractByCodeHash
      );
    },
    getSubDomain: async (
      params: DomainTypes.CallMethodParams<"getSubDomain">
    ): Promise<DomainTypes.CallMethodResult<"getSubDomain">> => {
      return callMethod(
        Domain,
        this,
        "getSubDomain",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createSubDomain: async (
      params: DomainTypes.SignExecuteMethodParams<"createSubDomain">
    ): Promise<DomainTypes.SignExecuteMethodResult<"createSubDomain">> => {
      return signExecuteMethod(Domain, this, "createSubDomain", params);
    },
    getSubDomain: async (
      params: DomainTypes.SignExecuteMethodParams<"getSubDomain">
    ): Promise<DomainTypes.SignExecuteMethodResult<"getSubDomain">> => {
      return signExecuteMethod(Domain, this, "getSubDomain", params);
    },
  };

  async multicall<Calls extends DomainTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DomainTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DomainTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DomainTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends DomainTypes.MultiCallParams | DomainTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Domain, this, callss, getContractByCodeHash);
  }
}
