/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as ErrorHandlingContractJson } from "../ErrorHandling.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace ErrorHandlingTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    assert: {
      params: CallContractParams<{ cond: boolean }>;
      result: CallContractResult<null>;
    };
    panicWithErrorCode: {
      params: CallContractParams<{ cond: boolean }>;
      result: CallContractResult<bigint>;
    };
    panicWithoutErrorCode: {
      params: CallContractParams<{ cond: boolean }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    assert: {
      params: SignExecuteContractMethodParams<{ cond: boolean }>;
      result: SignExecuteScriptTxResult;
    };
    panicWithErrorCode: {
      params: SignExecuteContractMethodParams<{ cond: boolean }>;
      result: SignExecuteScriptTxResult;
    };
    panicWithoutErrorCode: {
      params: SignExecuteContractMethodParams<{ cond: boolean }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<ErrorHandlingInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  consts = { ErrorCodes: { InvalidContractState: BigInt("0") } };

  at(address: string): ErrorHandlingInstance {
    return new ErrorHandlingInstance(address);
  }

  tests = {
    assert: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { cond: boolean }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "assert", params, getContractByCodeHash);
    },
    panicWithErrorCode: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { cond: boolean }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "panicWithErrorCode",
        params,
        getContractByCodeHash
      );
    },
    panicWithoutErrorCode: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { cond: boolean }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "panicWithoutErrorCode",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const ErrorHandling = new Factory(
  Contract.fromJson(
    ErrorHandlingContractJson,
    "",
    "f97a233d1a8d5bae3ff4d6e49cd9b4518cf1172b3eeede5ba9b0f2e3e4a0a37b",
    AllStructs
  )
);
registerContract(ErrorHandling);

// Use this class to interact with the blockchain
export class ErrorHandlingInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ErrorHandlingTypes.State> {
    return fetchContractState(ErrorHandling, this);
  }

  view = {
    assert: async (
      params: ErrorHandlingTypes.CallMethodParams<"assert">
    ): Promise<ErrorHandlingTypes.CallMethodResult<"assert">> => {
      return callMethod(
        ErrorHandling,
        this,
        "assert",
        params,
        getContractByCodeHash
      );
    },
    panicWithErrorCode: async (
      params: ErrorHandlingTypes.CallMethodParams<"panicWithErrorCode">
    ): Promise<ErrorHandlingTypes.CallMethodResult<"panicWithErrorCode">> => {
      return callMethod(
        ErrorHandling,
        this,
        "panicWithErrorCode",
        params,
        getContractByCodeHash
      );
    },
    panicWithoutErrorCode: async (
      params: ErrorHandlingTypes.CallMethodParams<"panicWithoutErrorCode">
    ): Promise<
      ErrorHandlingTypes.CallMethodResult<"panicWithoutErrorCode">
    > => {
      return callMethod(
        ErrorHandling,
        this,
        "panicWithoutErrorCode",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    assert: async (
      params: ErrorHandlingTypes.SignExecuteMethodParams<"assert">
    ): Promise<ErrorHandlingTypes.SignExecuteMethodResult<"assert">> => {
      return signExecuteMethod(ErrorHandling, this, "assert", params);
    },
    panicWithErrorCode: async (
      params: ErrorHandlingTypes.SignExecuteMethodParams<"panicWithErrorCode">
    ): Promise<
      ErrorHandlingTypes.SignExecuteMethodResult<"panicWithErrorCode">
    > => {
      return signExecuteMethod(
        ErrorHandling,
        this,
        "panicWithErrorCode",
        params
      );
    },
    panicWithoutErrorCode: async (
      params: ErrorHandlingTypes.SignExecuteMethodParams<"panicWithoutErrorCode">
    ): Promise<
      ErrorHandlingTypes.SignExecuteMethodResult<"panicWithoutErrorCode">
    > => {
      return signExecuteMethod(
        ErrorHandling,
        this,
        "panicWithoutErrorCode",
        params
      );
    },
  };

  async multicall<Calls extends ErrorHandlingTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ErrorHandlingTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends ErrorHandlingTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<ErrorHandlingTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | ErrorHandlingTypes.MultiCallParams
      | ErrorHandlingTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      ErrorHandling,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
