/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FancyTokenFactoryContractJson } from "../FancyTokenFactory.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace FancyTokenFactoryTypes {
  export type Fields = {
    fancyTokenTemplateId: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    mint: {
      params: CallContractParams<{ name: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    mint: {
      params: SignExecuteContractMethodParams<{ name: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FancyTokenFactoryInstance,
  FancyTokenFactoryTypes.Fields
> {
  encodeFields(fields: FancyTokenFactoryTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): FancyTokenFactoryInstance {
    return new FancyTokenFactoryInstance(address);
  }

  tests = {
    mint: async (
      params: TestContractParamsWithoutMaps<
        FancyTokenFactoryTypes.Fields,
        { name: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FancyTokenFactoryTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FancyTokenFactory = new Factory(
  Contract.fromJson(
    FancyTokenFactoryContractJson,
    "",
    "81c640586b906a08356a0b3da3818a0961344589f86d0ecd429b262b2c4b3317",
    AllStructs
  )
);
registerContract(FancyTokenFactory);

// Use this class to interact with the blockchain
export class FancyTokenFactoryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FancyTokenFactoryTypes.State> {
    return fetchContractState(FancyTokenFactory, this);
  }

  view = {
    mint: async (
      params: FancyTokenFactoryTypes.CallMethodParams<"mint">
    ): Promise<FancyTokenFactoryTypes.CallMethodResult<"mint">> => {
      return callMethod(
        FancyTokenFactory,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    mint: async (
      params: FancyTokenFactoryTypes.SignExecuteMethodParams<"mint">
    ): Promise<FancyTokenFactoryTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(FancyTokenFactory, this, "mint", params);
    },
  };
}
