/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FancyTokenContractJson } from "../FancyToken.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace FancyTokenTypes {
  export type Fields = {
    name: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    transferTokens: {
      params: CallContractParams<{ recipient: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    transferTokens: {
      params: SignExecuteContractMethodParams<{
        recipient: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FancyTokenInstance,
  FancyTokenTypes.Fields
> {
  encodeFields(fields: FancyTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): FancyTokenInstance {
    return new FancyTokenInstance(address);
  }

  tests = {
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<FancyTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    transferTokens: async (
      params: TestContractParamsWithoutMaps<
        FancyTokenTypes.Fields,
        { recipient: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "transferTokens", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FancyTokenTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FancyToken = new Factory(
  Contract.fromJson(
    FancyTokenContractJson,
    "",
    "68d65cfcb347d91ca13378da5f35efeb58832cbdc2e8aa536e4e89782b5ae0fa",
    AllStructs
  )
);
registerContract(FancyToken);

// Use this class to interact with the blockchain
export class FancyTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FancyTokenTypes.State> {
    return fetchContractState(FancyToken, this);
  }

  view = {
    getName: async (
      params?: FancyTokenTypes.CallMethodParams<"getName">
    ): Promise<FancyTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        FancyToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    transferTokens: async (
      params: FancyTokenTypes.CallMethodParams<"transferTokens">
    ): Promise<FancyTokenTypes.CallMethodResult<"transferTokens">> => {
      return callMethod(
        FancyToken,
        this,
        "transferTokens",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getName: async (
      params: FancyTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<FancyTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(FancyToken, this, "getName", params);
    },
    transferTokens: async (
      params: FancyTokenTypes.SignExecuteMethodParams<"transferTokens">
    ): Promise<FancyTokenTypes.SignExecuteMethodResult<"transferTokens">> => {
      return signExecuteMethod(FancyToken, this, "transferTokens", params);
    },
  };

  async multicall<Calls extends FancyTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FancyTokenTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FancyTokenTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FancyTokenTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FancyTokenTypes.MultiCallParams
      | FancyTokenTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FancyToken,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
