/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FibContractJson } from "../Fib.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace FibTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    cal: {
      params: CallContractParams<{ n: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    cal: {
      params: SignExecuteContractMethodParams<{ n: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<FibInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): FibInstance {
    return new FibInstance(address);
  }

  tests = {
    cal: async (
      params: Omit<
        TestContractParamsWithoutMaps<never, { n: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "cal", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Fib = new Factory(
  Contract.fromJson(
    FibContractJson,
    "",
    "66afac8a6a1f0040eac054cf14d3e51c8437d36c0b9aa4db391da4519315a8ae",
    AllStructs
  )
);
registerContract(Fib);

// Use this class to interact with the blockchain
export class FibInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FibTypes.State> {
    return fetchContractState(Fib, this);
  }

  view = {
    cal: async (
      params: FibTypes.CallMethodParams<"cal">
    ): Promise<FibTypes.CallMethodResult<"cal">> => {
      return callMethod(Fib, this, "cal", params, getContractByCodeHash);
    },
  };

  transact = {
    cal: async (
      params: FibTypes.SignExecuteMethodParams<"cal">
    ): Promise<FibTypes.SignExecuteMethodResult<"cal">> => {
      return signExecuteMethod(Fib, this, "cal", params);
    },
  };

  async multicall<Calls extends FibTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FibTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FibTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FibTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends FibTypes.MultiCallParams | FibTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Fib, this, callss, getContractByCodeHash);
  }
}
