/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FunctionCallsContractJson } from "../FunctionCalls.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace FunctionCallsTypes {
  export type Fields = {
    fib: HexString;
    result: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    runFib: {
      params: CallContractParams<{ n: bigint }>;
      result: CallContractResult<null>;
    };
    updateResult: {
      params: CallContractParams<{ res: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    runFib: {
      params: SignExecuteContractMethodParams<{ n: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    updateResult: {
      params: SignExecuteContractMethodParams<{ res: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FunctionCallsInstance,
  FunctionCallsTypes.Fields
> {
  encodeFields(fields: FunctionCallsTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): FunctionCallsInstance {
    return new FunctionCallsInstance(address);
  }

  tests = {
    runFib: async (
      params: TestContractParamsWithoutMaps<
        FunctionCallsTypes.Fields,
        { n: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "runFib", params, getContractByCodeHash);
    },
    updateResult: async (
      params: TestContractParamsWithoutMaps<
        FunctionCallsTypes.Fields,
        { res: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateResult", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FunctionCallsTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FunctionCalls = new Factory(
  Contract.fromJson(
    FunctionCallsContractJson,
    "",
    "2e648be17ab5c067881bb844d28eab423f93df59142f2d9dbc32afd684dcba21",
    AllStructs
  )
);
registerContract(FunctionCalls);

// Use this class to interact with the blockchain
export class FunctionCallsInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FunctionCallsTypes.State> {
    return fetchContractState(FunctionCalls, this);
  }

  view = {
    runFib: async (
      params: FunctionCallsTypes.CallMethodParams<"runFib">
    ): Promise<FunctionCallsTypes.CallMethodResult<"runFib">> => {
      return callMethod(
        FunctionCalls,
        this,
        "runFib",
        params,
        getContractByCodeHash
      );
    },
    updateResult: async (
      params: FunctionCallsTypes.CallMethodParams<"updateResult">
    ): Promise<FunctionCallsTypes.CallMethodResult<"updateResult">> => {
      return callMethod(
        FunctionCalls,
        this,
        "updateResult",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    runFib: async (
      params: FunctionCallsTypes.SignExecuteMethodParams<"runFib">
    ): Promise<FunctionCallsTypes.SignExecuteMethodResult<"runFib">> => {
      return signExecuteMethod(FunctionCalls, this, "runFib", params);
    },
    updateResult: async (
      params: FunctionCallsTypes.SignExecuteMethodParams<"updateResult">
    ): Promise<FunctionCallsTypes.SignExecuteMethodResult<"updateResult">> => {
      return signExecuteMethod(FunctionCalls, this, "updateResult", params);
    },
  };
}
