/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as HelloWeb3ContractJson } from "../HelloWeb3.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace HelloWeb3Types {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    main: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    main: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<HelloWeb3Instance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): HelloWeb3Instance {
    return new HelloWeb3Instance(address);
  }

  tests = {
    main: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "testArgs" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "main",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const HelloWeb3 = new Factory(
  Contract.fromJson(
    HelloWeb3ContractJson,
    "=4-2+19=11-1+2=10+7e010b48656c6c6f205765623321",
    "6727db29e2c591031c5f6e22aa311b1f54d2dff031869d1d16c3b9149e06c805",
    AllStructs
  )
);
registerContract(HelloWeb3);

// Use this class to interact with the blockchain
export class HelloWeb3Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<HelloWeb3Types.State> {
    return fetchContractState(HelloWeb3, this);
  }

  view = {
    main: async (
      params?: HelloWeb3Types.CallMethodParams<"main">
    ): Promise<HelloWeb3Types.CallMethodResult<"main">> => {
      return callMethod(
        HelloWeb3,
        this,
        "main",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    main: async (
      params: HelloWeb3Types.SignExecuteMethodParams<"main">
    ): Promise<HelloWeb3Types.SignExecuteMethodResult<"main">> => {
      return signExecuteMethod(HelloWeb3, this, "main", params);
    },
  };
}
