/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as InternalContractJson } from "../Internal.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace InternalTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    call: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    call: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<InternalInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): InternalInstance {
    return new InternalInstance(address);
  }

  tests = {
    call: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(
        this,
        "call",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Internal = new Factory(
  Contract.fromJson(
    InternalContractJson,
    "",
    "092813100f04c0e237f43fab51043db392ff88d094cf786cfb6c6c79d121947b",
    AllStructs
  )
);
registerContract(Internal);

// Use this class to interact with the blockchain
export class InternalInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<InternalTypes.State> {
    return fetchContractState(Internal, this);
  }

  view = {
    call: async (
      params?: InternalTypes.CallMethodParams<"call">
    ): Promise<InternalTypes.CallMethodResult<"call">> => {
      return callMethod(
        Internal,
        this,
        "call",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    call: async (
      params: InternalTypes.SignExecuteMethodParams<"call">
    ): Promise<InternalTypes.SignExecuteMethodResult<"call">> => {
      return signExecuteMethod(Internal, this, "call", params);
    },
  };

  async multicall<Calls extends InternalTypes.MultiCallParams>(
    calls: Calls
  ): Promise<InternalTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends InternalTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<InternalTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | InternalTypes.MultiCallParams
      | InternalTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      Internal,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
