/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as LoopContractJson } from "../Loop.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace LoopTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    whileStmt: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    forStmt: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    whileStmt: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    forStmt: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<LoopInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): LoopInstance {
    return new LoopInstance(address);
  }

  tests = {
    whileStmt: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "whileStmt",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    forStmt: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "forStmt",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Loop = new Factory(
  Contract.fromJson(
    LoopContractJson,
    "",
    "6c1aa99473cb6cb4fb2be43c55169e2e2821972f122eb94e1b1722c50241ea60",
    AllStructs
  )
);
registerContract(Loop);

// Use this class to interact with the blockchain
export class LoopInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<LoopTypes.State> {
    return fetchContractState(Loop, this);
  }

  view = {
    whileStmt: async (
      params?: LoopTypes.CallMethodParams<"whileStmt">
    ): Promise<LoopTypes.CallMethodResult<"whileStmt">> => {
      return callMethod(
        Loop,
        this,
        "whileStmt",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    forStmt: async (
      params?: LoopTypes.CallMethodParams<"forStmt">
    ): Promise<LoopTypes.CallMethodResult<"forStmt">> => {
      return callMethod(
        Loop,
        this,
        "forStmt",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    whileStmt: async (
      params: LoopTypes.SignExecuteMethodParams<"whileStmt">
    ): Promise<LoopTypes.SignExecuteMethodResult<"whileStmt">> => {
      return signExecuteMethod(Loop, this, "whileStmt", params);
    },
    forStmt: async (
      params: LoopTypes.SignExecuteMethodParams<"forStmt">
    ): Promise<LoopTypes.SignExecuteMethodResult<"forStmt">> => {
      return signExecuteMethod(Loop, this, "forStmt", params);
    },
  };

  async multicall<Calls extends LoopTypes.MultiCallParams>(
    calls: Calls
  ): Promise<LoopTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends LoopTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<LoopTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends LoopTypes.MultiCallParams | LoopTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Loop, this, callss, getContractByCodeHash);
  }
}
