/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as MyTokenContractJson } from "../MyToken.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace MyTokenTypes {
  export type Fields = {
    name: HexString;
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export type TransferEvent = ContractEvent<{
    to: Address;
    amount: bigint;
    version: bigint;
  }>;

  export interface CallMethodTable {
    withdraw: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    updateOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    withdraw: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    updateOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<MyTokenInstance, MyTokenTypes.Fields> {
  encodeFields(fields: MyTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { Transfer: 0 };
  consts = {
    VERSION: BigInt("0"),
    ErrorCodes: { INVALID_CALLER: BigInt("0") },
  };

  at(address: string): MyTokenInstance {
    return new MyTokenInstance(address);
  }

  tests = {
    withdraw: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    updateOwner: async (
      params: TestContractParamsWithoutMaps<
        MyTokenTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateOwner", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getOwner: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getOwner", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: MyTokenTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const MyToken = new Factory(
  Contract.fromJson(
    MyTokenContractJson,
    "",
    "4794d2ec9ca21bb94d985f5174670257277ea958251fcb4ba4269bdac38ab2e4",
    AllStructs
  )
);
registerContract(MyToken);

// Use this class to interact with the blockchain
export class MyTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<MyTokenTypes.State> {
    return fetchContractState(MyToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeTransferEvent(
    options: EventSubscribeOptions<MyTokenTypes.TransferEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      MyToken.contract,
      this,
      options,
      "Transfer",
      fromCount
    );
  }

  view = {
    withdraw: async (
      params?: MyTokenTypes.CallMethodParams<"withdraw">
    ): Promise<MyTokenTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        MyToken,
        this,
        "withdraw",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    updateOwner: async (
      params: MyTokenTypes.CallMethodParams<"updateOwner">
    ): Promise<MyTokenTypes.CallMethodResult<"updateOwner">> => {
      return callMethod(
        MyToken,
        this,
        "updateOwner",
        params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: MyTokenTypes.CallMethodParams<"getName">
    ): Promise<MyTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        MyToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOwner: async (
      params?: MyTokenTypes.CallMethodParams<"getOwner">
    ): Promise<MyTokenTypes.CallMethodResult<"getOwner">> => {
      return callMethod(
        MyToken,
        this,
        "getOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    withdraw: async (
      params: MyTokenTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(MyToken, this, "withdraw", params);
    },
    updateOwner: async (
      params: MyTokenTypes.SignExecuteMethodParams<"updateOwner">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"updateOwner">> => {
      return signExecuteMethod(MyToken, this, "updateOwner", params);
    },
    getName: async (
      params: MyTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(MyToken, this, "getName", params);
    },
    getOwner: async (
      params: MyTokenTypes.SignExecuteMethodParams<"getOwner">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"getOwner">> => {
      return signExecuteMethod(MyToken, this, "getOwner", params);
    },
  };

  async multicall<Calls extends MyTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<MyTokenTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends MyTokenTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<MyTokenTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends MyTokenTypes.MultiCallParams | MyTokenTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(MyToken, this, callss, getContractByCodeHash);
  }
}
