/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as OldCodeContractJson } from "../OldCode.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace OldCodeTypes {
  export type Fields = {
    owner: Address;
    n: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    get: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    migrate: {
      params: CallContractParams<{ newCode: HexString }>;
      result: CallContractResult<null>;
    };
    migrateWithFields: {
      params: CallContractParams<{
        newCode: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    get: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrate: {
      params: SignExecuteContractMethodParams<{ newCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFields: {
      params: SignExecuteContractMethodParams<{
        newCode: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<OldCodeInstance, OldCodeTypes.Fields> {
  encodeFields(fields: OldCodeTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): OldCodeInstance {
    return new OldCodeInstance(address);
  }

  tests = {
    get: async (
      params: Omit<
        TestContractParamsWithoutMaps<OldCodeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "get", params, getContractByCodeHash);
    },
    migrate: async (
      params: TestContractParamsWithoutMaps<
        OldCodeTypes.Fields,
        { newCode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "migrate", params, getContractByCodeHash);
    },
    migrateWithFields: async (
      params: TestContractParamsWithoutMaps<
        OldCodeTypes.Fields,
        { newCode: HexString; immFields: HexString; mutFields: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: OldCodeTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const OldCode = new Factory(
  Contract.fromJson(
    OldCodeContractJson,
    "",
    "029d9cc9b9a0129893b0fb1d8d77d8193e865c219d50749cd04a64351d71da47",
    AllStructs
  )
);
registerContract(OldCode);

// Use this class to interact with the blockchain
export class OldCodeInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<OldCodeTypes.State> {
    return fetchContractState(OldCode, this);
  }

  view = {
    get: async (
      params?: OldCodeTypes.CallMethodParams<"get">
    ): Promise<OldCodeTypes.CallMethodResult<"get">> => {
      return callMethod(
        OldCode,
        this,
        "get",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrate: async (
      params: OldCodeTypes.CallMethodParams<"migrate">
    ): Promise<OldCodeTypes.CallMethodResult<"migrate">> => {
      return callMethod(
        OldCode,
        this,
        "migrate",
        params,
        getContractByCodeHash
      );
    },
    migrateWithFields: async (
      params: OldCodeTypes.CallMethodParams<"migrateWithFields">
    ): Promise<OldCodeTypes.CallMethodResult<"migrateWithFields">> => {
      return callMethod(
        OldCode,
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    get: async (
      params: OldCodeTypes.SignExecuteMethodParams<"get">
    ): Promise<OldCodeTypes.SignExecuteMethodResult<"get">> => {
      return signExecuteMethod(OldCode, this, "get", params);
    },
    migrate: async (
      params: OldCodeTypes.SignExecuteMethodParams<"migrate">
    ): Promise<OldCodeTypes.SignExecuteMethodResult<"migrate">> => {
      return signExecuteMethod(OldCode, this, "migrate", params);
    },
    migrateWithFields: async (
      params: OldCodeTypes.SignExecuteMethodParams<"migrateWithFields">
    ): Promise<OldCodeTypes.SignExecuteMethodResult<"migrateWithFields">> => {
      return signExecuteMethod(OldCode, this, "migrateWithFields", params);
    },
  };

  async multicall<Calls extends OldCodeTypes.MultiCallParams>(
    calls: Calls
  ): Promise<OldCodeTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends OldCodeTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<OldCodeTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends OldCodeTypes.MultiCallParams | OldCodeTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(OldCode, this, callss, getContractByCodeHash);
  }
}
