/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as RouterContractJson } from "../Router.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace RouterTypes {
  export type Fields = {
    internal: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    default: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    preserveCaller: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    default: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    preserveCaller: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<RouterInstance, RouterTypes.Fields> {
  encodeFields(fields: RouterTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): RouterInstance {
    return new RouterInstance(address);
  }

  tests = {
    default: async (
      params: Omit<
        TestContractParamsWithoutMaps<RouterTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "default", params, getContractByCodeHash);
    },
    preserveCaller: async (
      params: Omit<
        TestContractParamsWithoutMaps<RouterTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "preserveCaller", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: RouterTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Router = new Factory(
  Contract.fromJson(
    RouterContractJson,
    "",
    "8827f93b0d8d3549eb4b2b7fc863e08bd3bb10ae937f3f4e022e43ebea330d7a",
    AllStructs
  )
);
registerContract(Router);

// Use this class to interact with the blockchain
export class RouterInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<RouterTypes.State> {
    return fetchContractState(Router, this);
  }

  view = {
    default: async (
      params?: RouterTypes.CallMethodParams<"default">
    ): Promise<RouterTypes.CallMethodResult<"default">> => {
      return callMethod(
        Router,
        this,
        "default",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    preserveCaller: async (
      params?: RouterTypes.CallMethodParams<"preserveCaller">
    ): Promise<RouterTypes.CallMethodResult<"preserveCaller">> => {
      return callMethod(
        Router,
        this,
        "preserveCaller",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    default: async (
      params: RouterTypes.SignExecuteMethodParams<"default">
    ): Promise<RouterTypes.SignExecuteMethodResult<"default">> => {
      return signExecuteMethod(Router, this, "default", params);
    },
    preserveCaller: async (
      params: RouterTypes.SignExecuteMethodParams<"preserveCaller">
    ): Promise<RouterTypes.SignExecuteMethodResult<"preserveCaller">> => {
      return signExecuteMethod(Router, this, "preserveCaller", params);
    },
  };

  async multicall<Calls extends RouterTypes.MultiCallParams>(
    calls: Calls
  ): Promise<RouterTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends RouterTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<RouterTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends RouterTypes.MultiCallParams | RouterTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Router, this, callss, getContractByCodeHash);
  }
}
