/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as ChainScriptJson } from "../Chain.ral.json";
import { default as DepositTwiceScriptJson } from "../DepositTwice.ral.json";
import { default as WithdrawScriptJson } from "../Withdraw.ral.json";
import { Bar, Foo, AllStructs } from "./types";

export const Chain = new ExecutableScript<{}>(
  Script.fromJson(ChainScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const DepositTwice = new ExecutableScript<{ contract: HexString }>(
  Script.fromJson(DepositTwiceScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const Withdraw = new ExecutableScript<{
  token: HexString;
  amount: bigint;
}>(Script.fromJson(WithdrawScriptJson, "", AllStructs), getContractByCodeHash);
