/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as SoftwareEngineerContractJson } from "../SoftwareEngineer.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace SoftwareEngineerTypes {
  export type Fields = {
    name: HexString;
    id: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    pay: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<bigint>;
    };
    status: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getSpecialization: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getStandardWorkingHours: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    pay: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    status: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getSpecialization: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getStandardWorkingHours: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  SoftwareEngineerInstance,
  SoftwareEngineerTypes.Fields
> {
  encodeFields(fields: SoftwareEngineerTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): SoftwareEngineerInstance {
    return new SoftwareEngineerInstance(address);
  }

  tests = {
    pay: async (
      params: TestContractParamsWithoutMaps<
        SoftwareEngineerTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "pay", params, getContractByCodeHash);
    },
    status: async (
      params: Omit<
        TestContractParamsWithoutMaps<SoftwareEngineerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "status", params, getContractByCodeHash);
    },
    getSpecialization: async (
      params: Omit<
        TestContractParamsWithoutMaps<SoftwareEngineerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getSpecialization",
        params,
        getContractByCodeHash
      );
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<SoftwareEngineerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getId: async (
      params: Omit<
        TestContractParamsWithoutMaps<SoftwareEngineerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getId", params, getContractByCodeHash);
    },
    getStandardWorkingHours: async (
      params: Omit<
        TestContractParamsWithoutMaps<SoftwareEngineerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getStandardWorkingHours",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: SoftwareEngineerTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const SoftwareEngineer = new Factory(
  Contract.fromJson(
    SoftwareEngineerContractJson,
    "",
    "b01e49bf45d5d736cffc6383420e9fe4bb260b2b045fa402c588aeff5fdc10cd",
    AllStructs
  )
);
registerContract(SoftwareEngineer);

// Use this class to interact with the blockchain
export class SoftwareEngineerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SoftwareEngineerTypes.State> {
    return fetchContractState(SoftwareEngineer, this);
  }

  view = {
    pay: async (
      params: SoftwareEngineerTypes.CallMethodParams<"pay">
    ): Promise<SoftwareEngineerTypes.CallMethodResult<"pay">> => {
      return callMethod(
        SoftwareEngineer,
        this,
        "pay",
        params,
        getContractByCodeHash
      );
    },
    status: async (
      params?: SoftwareEngineerTypes.CallMethodParams<"status">
    ): Promise<SoftwareEngineerTypes.CallMethodResult<"status">> => {
      return callMethod(
        SoftwareEngineer,
        this,
        "status",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSpecialization: async (
      params?: SoftwareEngineerTypes.CallMethodParams<"getSpecialization">
    ): Promise<SoftwareEngineerTypes.CallMethodResult<"getSpecialization">> => {
      return callMethod(
        SoftwareEngineer,
        this,
        "getSpecialization",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: SoftwareEngineerTypes.CallMethodParams<"getName">
    ): Promise<SoftwareEngineerTypes.CallMethodResult<"getName">> => {
      return callMethod(
        SoftwareEngineer,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getId: async (
      params?: SoftwareEngineerTypes.CallMethodParams<"getId">
    ): Promise<SoftwareEngineerTypes.CallMethodResult<"getId">> => {
      return callMethod(
        SoftwareEngineer,
        this,
        "getId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getStandardWorkingHours: async (
      params?: SoftwareEngineerTypes.CallMethodParams<"getStandardWorkingHours">
    ): Promise<
      SoftwareEngineerTypes.CallMethodResult<"getStandardWorkingHours">
    > => {
      return callMethod(
        SoftwareEngineer,
        this,
        "getStandardWorkingHours",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    pay: async (
      params: SoftwareEngineerTypes.SignExecuteMethodParams<"pay">
    ): Promise<SoftwareEngineerTypes.SignExecuteMethodResult<"pay">> => {
      return signExecuteMethod(SoftwareEngineer, this, "pay", params);
    },
    status: async (
      params: SoftwareEngineerTypes.SignExecuteMethodParams<"status">
    ): Promise<SoftwareEngineerTypes.SignExecuteMethodResult<"status">> => {
      return signExecuteMethod(SoftwareEngineer, this, "status", params);
    },
    getSpecialization: async (
      params: SoftwareEngineerTypes.SignExecuteMethodParams<"getSpecialization">
    ): Promise<
      SoftwareEngineerTypes.SignExecuteMethodResult<"getSpecialization">
    > => {
      return signExecuteMethod(
        SoftwareEngineer,
        this,
        "getSpecialization",
        params
      );
    },
    getName: async (
      params: SoftwareEngineerTypes.SignExecuteMethodParams<"getName">
    ): Promise<SoftwareEngineerTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(SoftwareEngineer, this, "getName", params);
    },
    getId: async (
      params: SoftwareEngineerTypes.SignExecuteMethodParams<"getId">
    ): Promise<SoftwareEngineerTypes.SignExecuteMethodResult<"getId">> => {
      return signExecuteMethod(SoftwareEngineer, this, "getId", params);
    },
    getStandardWorkingHours: async (
      params: SoftwareEngineerTypes.SignExecuteMethodParams<"getStandardWorkingHours">
    ): Promise<
      SoftwareEngineerTypes.SignExecuteMethodResult<"getStandardWorkingHours">
    > => {
      return signExecuteMethod(
        SoftwareEngineer,
        this,
        "getStandardWorkingHours",
        params
      );
    },
  };

  async multicall<Calls extends SoftwareEngineerTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SoftwareEngineerTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends SoftwareEngineerTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<SoftwareEngineerTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | SoftwareEngineerTypes.MultiCallParams
      | SoftwareEngineerTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      SoftwareEngineer,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
