/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as StructContractJson } from "../Struct.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace StructTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    test1: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    test2: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    test3: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    test1: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    test2: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    test3: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<StructInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): StructInstance {
    return new StructInstance(address);
  }

  tests = {
    test1: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "test1",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    test2: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "test2",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    test3: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "test3",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Struct = new Factory(
  Contract.fromJson(
    StructContractJson,
    "=6-4+5=1-1=3-1+c40f8=11-1+e=96+7e011c546573742031207375636365737366756c20666f7220537472756374=11-1+6=68+7e011c546573742032207375636365737366756c20666f7220537472756374=13-1+4=108+7e011c546573742033207375636365737366756c20666f7220537472756374",
    "47f6955714f57997ff90e1f2d261615592f0670c96f1a6cc5c0e635bd4ceff5c",
    AllStructs
  )
);
registerContract(Struct);

// Use this class to interact with the blockchain
export class StructInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<StructTypes.State> {
    return fetchContractState(Struct, this);
  }

  view = {
    test1: async (
      params?: StructTypes.CallMethodParams<"test1">
    ): Promise<StructTypes.CallMethodResult<"test1">> => {
      return callMethod(
        Struct,
        this,
        "test1",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    test2: async (
      params?: StructTypes.CallMethodParams<"test2">
    ): Promise<StructTypes.CallMethodResult<"test2">> => {
      return callMethod(
        Struct,
        this,
        "test2",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    test3: async (
      params?: StructTypes.CallMethodParams<"test3">
    ): Promise<StructTypes.CallMethodResult<"test3">> => {
      return callMethod(
        Struct,
        this,
        "test3",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    test1: async (
      params: StructTypes.SignExecuteMethodParams<"test1">
    ): Promise<StructTypes.SignExecuteMethodResult<"test1">> => {
      return signExecuteMethod(Struct, this, "test1", params);
    },
    test2: async (
      params: StructTypes.SignExecuteMethodParams<"test2">
    ): Promise<StructTypes.SignExecuteMethodResult<"test2">> => {
      return signExecuteMethod(Struct, this, "test2", params);
    },
    test3: async (
      params: StructTypes.SignExecuteMethodParams<"test3">
    ): Promise<StructTypes.SignExecuteMethodResult<"test3">> => {
      return signExecuteMethod(Struct, this, "test3", params);
    },
  };
}
