/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as SubDomainContractJson } from "../SubDomain.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace SubDomainTypes {
  export type Fields = {
    url: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getUrl: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getUrl: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  SubDomainInstance,
  SubDomainTypes.Fields
> {
  encodeFields(fields: SubDomainTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): SubDomainInstance {
    return new SubDomainInstance(address);
  }

  tests = {
    getUrl: async (
      params: Omit<
        TestContractParamsWithoutMaps<SubDomainTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getUrl", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: SubDomainTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const SubDomain = new Factory(
  Contract.fromJson(
    SubDomainContractJson,
    "",
    "fced46b77d552aaf826aae11354f3218c7420adfc917cb8159d6babf3e73e606",
    AllStructs
  )
);
registerContract(SubDomain);

// Use this class to interact with the blockchain
export class SubDomainInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SubDomainTypes.State> {
    return fetchContractState(SubDomain, this);
  }

  view = {
    getUrl: async (
      params?: SubDomainTypes.CallMethodParams<"getUrl">
    ): Promise<SubDomainTypes.CallMethodResult<"getUrl">> => {
      return callMethod(
        SubDomain,
        this,
        "getUrl",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getUrl: async (
      params: SubDomainTypes.SignExecuteMethodParams<"getUrl">
    ): Promise<SubDomainTypes.SignExecuteMethodResult<"getUrl">> => {
      return signExecuteMethod(SubDomain, this, "getUrl", params);
    },
  };

  async multicall<Calls extends SubDomainTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SubDomainTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends SubDomainTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<SubDomainTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | SubDomainTypes.MultiCallParams
      | SubDomainTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      SubDomain,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
