/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as SwapContractJson } from "../Swap.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace SwapTypes {
  export type Fields = {
    tokenId1: HexString;
    tokenId2: HexString;
    token1Reserve: bigint;
    token2Reserve: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    addLiquidity: {
      params: CallContractParams<{
        lp: Address;
        token1Amount: bigint;
        token2Amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    swap: {
      params: CallContractParams<{
        buyer: Address;
        tokenId: HexString;
        tokenAmount: bigint;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    addLiquidity: {
      params: SignExecuteContractMethodParams<{
        lp: Address;
        token1Amount: bigint;
        token2Amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    swap: {
      params: SignExecuteContractMethodParams<{
        buyer: Address;
        tokenId: HexString;
        tokenAmount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<SwapInstance, SwapTypes.Fields> {
  encodeFields(fields: SwapTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): SwapInstance {
    return new SwapInstance(address);
  }

  tests = {
    addLiquidity: async (
      params: TestContractParamsWithoutMaps<
        SwapTypes.Fields,
        { lp: Address; token1Amount: bigint; token2Amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "addLiquidity", params, getContractByCodeHash);
    },
    swap: async (
      params: TestContractParamsWithoutMaps<
        SwapTypes.Fields,
        { buyer: Address; tokenId: HexString; tokenAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "swap", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: SwapTypes.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Swap = new Factory(
  Contract.fromJson(
    SwapContractJson,
    "",
    "c8e1bd347ee2f8561eaac9478d2ff7bb1899099261e436ce4e324e8c27827af8",
    AllStructs
  )
);
registerContract(Swap);

// Use this class to interact with the blockchain
export class SwapInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SwapTypes.State> {
    return fetchContractState(Swap, this);
  }

  view = {
    addLiquidity: async (
      params: SwapTypes.CallMethodParams<"addLiquidity">
    ): Promise<SwapTypes.CallMethodResult<"addLiquidity">> => {
      return callMethod(
        Swap,
        this,
        "addLiquidity",
        params,
        getContractByCodeHash
      );
    },
    swap: async (
      params: SwapTypes.CallMethodParams<"swap">
    ): Promise<SwapTypes.CallMethodResult<"swap">> => {
      return callMethod(Swap, this, "swap", params, getContractByCodeHash);
    },
  };

  transact = {
    addLiquidity: async (
      params: SwapTypes.SignExecuteMethodParams<"addLiquidity">
    ): Promise<SwapTypes.SignExecuteMethodResult<"addLiquidity">> => {
      return signExecuteMethod(Swap, this, "addLiquidity", params);
    },
    swap: async (
      params: SwapTypes.SignExecuteMethodParams<"swap">
    ): Promise<SwapTypes.SignExecuteMethodResult<"swap">> => {
      return signExecuteMethod(Swap, this, "swap", params);
    },
  };
}
