/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TupleExampleContractJson } from "../TupleExample.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace TupleExampleTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    createTuple: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, HexString, boolean]>;
    };
    test: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createTuple: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    test: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TupleExampleInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): TupleExampleInstance {
    return new TupleExampleInstance(address);
  }

  tests = {
    createTuple: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, HexString, boolean]>> => {
      return testMethod(
        this,
        "createTuple",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    test: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "test",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TupleExample = new Factory(
  Contract.fromJson(
    TupleExampleContractJson,
    "=8-2+6d=63-1+9=106+7e01155475706c652074657374207375636365737366756c",
    "9770b3222cd87a67fb5f91857a2cd553281f5978c64aee64e699e9156ef5ab30",
    AllStructs
  )
);
registerContract(TupleExample);

// Use this class to interact with the blockchain
export class TupleExampleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TupleExampleTypes.State> {
    return fetchContractState(TupleExample, this);
  }

  view = {
    createTuple: async (
      params?: TupleExampleTypes.CallMethodParams<"createTuple">
    ): Promise<TupleExampleTypes.CallMethodResult<"createTuple">> => {
      return callMethod(
        TupleExample,
        this,
        "createTuple",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    test: async (
      params?: TupleExampleTypes.CallMethodParams<"test">
    ): Promise<TupleExampleTypes.CallMethodResult<"test">> => {
      return callMethod(
        TupleExample,
        this,
        "test",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createTuple: async (
      params: TupleExampleTypes.SignExecuteMethodParams<"createTuple">
    ): Promise<TupleExampleTypes.SignExecuteMethodResult<"createTuple">> => {
      return signExecuteMethod(TupleExample, this, "createTuple", params);
    },
    test: async (
      params: TupleExampleTypes.SignExecuteMethodParams<"test">
    ): Promise<TupleExampleTypes.SignExecuteMethodResult<"test">> => {
      return signExecuteMethod(TupleExample, this, "test", params);
    },
  };

  async multicall<Calls extends TupleExampleTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TupleExampleTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends TupleExampleTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<TupleExampleTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | TupleExampleTypes.MultiCallParams
      | TupleExampleTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      TupleExample,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
