/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as UnitTestContractJson } from "../UnitTest.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bar, Foo, AllStructs } from "./types";

// Custom types for the contract
export namespace UnitTestTypes {
  export type Fields = {
    count: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    add: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<bigint>;
    };
    divide: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<bigint>;
    };
    isAdult: {
      params: CallContractParams<{ age: bigint }>;
      result: CallContractResult<boolean>;
    };
    increment: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    add: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    divide: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    isAdult: {
      params: SignExecuteContractMethodParams<{ age: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    increment: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<UnitTestInstance, UnitTestTypes.Fields> {
  encodeFields(fields: UnitTestTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): UnitTestInstance {
    return new UnitTestInstance(address);
  }

  tests = {
    add: async (
      params: TestContractParamsWithoutMaps<
        UnitTestTypes.Fields,
        { a: bigint; b: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "add", params, getContractByCodeHash);
    },
    divide: async (
      params: TestContractParamsWithoutMaps<
        UnitTestTypes.Fields,
        { a: bigint; b: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "divide", params, getContractByCodeHash);
    },
    isAdult: async (
      params: TestContractParamsWithoutMaps<
        UnitTestTypes.Fields,
        { age: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isAdult", params, getContractByCodeHash);
    },
    increment: async (
      params: Omit<
        TestContractParamsWithoutMaps<UnitTestTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "increment", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: UnitTestTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const UnitTest = new Factory(
  Contract.fromJson(
    UnitTestContractJson,
    "",
    "a894d6453b5f062d3bebef09be783e28f5c93beca8f20df4b91dfe89d514a5cb",
    AllStructs
  )
);
registerContract(UnitTest);

// Use this class to interact with the blockchain
export class UnitTestInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<UnitTestTypes.State> {
    return fetchContractState(UnitTest, this);
  }

  view = {
    add: async (
      params: UnitTestTypes.CallMethodParams<"add">
    ): Promise<UnitTestTypes.CallMethodResult<"add">> => {
      return callMethod(UnitTest, this, "add", params, getContractByCodeHash);
    },
    divide: async (
      params: UnitTestTypes.CallMethodParams<"divide">
    ): Promise<UnitTestTypes.CallMethodResult<"divide">> => {
      return callMethod(
        UnitTest,
        this,
        "divide",
        params,
        getContractByCodeHash
      );
    },
    isAdult: async (
      params: UnitTestTypes.CallMethodParams<"isAdult">
    ): Promise<UnitTestTypes.CallMethodResult<"isAdult">> => {
      return callMethod(
        UnitTest,
        this,
        "isAdult",
        params,
        getContractByCodeHash
      );
    },
    increment: async (
      params?: UnitTestTypes.CallMethodParams<"increment">
    ): Promise<UnitTestTypes.CallMethodResult<"increment">> => {
      return callMethod(
        UnitTest,
        this,
        "increment",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    add: async (
      params: UnitTestTypes.SignExecuteMethodParams<"add">
    ): Promise<UnitTestTypes.SignExecuteMethodResult<"add">> => {
      return signExecuteMethod(UnitTest, this, "add", params);
    },
    divide: async (
      params: UnitTestTypes.SignExecuteMethodParams<"divide">
    ): Promise<UnitTestTypes.SignExecuteMethodResult<"divide">> => {
      return signExecuteMethod(UnitTest, this, "divide", params);
    },
    isAdult: async (
      params: UnitTestTypes.SignExecuteMethodParams<"isAdult">
    ): Promise<UnitTestTypes.SignExecuteMethodResult<"isAdult">> => {
      return signExecuteMethod(UnitTest, this, "isAdult", params);
    },
    increment: async (
      params: UnitTestTypes.SignExecuteMethodParams<"increment">
    ): Promise<UnitTestTypes.SignExecuteMethodResult<"increment">> => {
      return signExecuteMethod(UnitTest, this, "increment", params);
    },
  };

  async multicall<Calls extends UnitTestTypes.MultiCallParams>(
    calls: Calls
  ): Promise<UnitTestTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends UnitTestTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<UnitTestTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | UnitTestTypes.MultiCallParams
      | UnitTestTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      UnitTest,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
